### ISSUE TITLE
Decide what displayNames to use for different actions

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-addons#3]

**Comment by christianalfoni** [comment]
This is working?

**Comment by garth** [comment]
@christianalfoni  it looks like you added displayName support yesterday, so I guess we can add this in now?

@Guria which actions do think would need the displayName to be explicitly set?

**Comment by christianalfoni** [comment]
Jup, this is in now and documented under "Factories" on the webpage as that is where you most likely will use them :)

**Comment by Guria** [comment]
@garth I plan to play with addons in near future. will try to determine which actions deserves displayName an dump my thoughts here

**Comment by garth** [comment]
Since displayNames are taken from the function names and all cerebral-addon action functions are named I don't think that it is necessary to name them via displayName.
